server:
  port: 1001
spring:
  datasource:
    url: jdbc:mysql://rds:3306/eventAdvisorDb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root