server:
  port: 8080
application:
  name: event-advisor
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventAdvisorDb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    jpa:
      show-sql: on
      generate-ddl: on
      properties.hibernate:
        format_sql: true
        use_sql_comments: true
  liquibase:
    change-log: classpath:db.changelog-master.xml

logging:
  level:
    root: INFO

management:
  endpoints:
    web.exposure.include: health, metrics

public.api.url: https://www.berlin.de/sen/web/service/maerkte-feste/strassen-volksfeste/index.php/index.gjson?q=&ipp=100000