server:
  port: 8080
application:
  name: event-advisor
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventAdvisorDb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    jpa:
      show-sql: on
      generate-ddl: on
      properties.hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: info

management:
  endpoints:
    web.exposure.include: health, metrics